---
title: "CTD Meta Processing"
author: "Abby Lewis"
date: "12/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(akima)
library(colorRamps)
library(rLakeAnalyzer)
library(readxl)
```

Pull in CTD data from EDI and plot changes resulting from drawdown in 2022, 2021 control


Read data from EDI
```{r}
ctd_edi <- read.csv("https://pasta.lternet.edu/package/data/eml/edi/200/13/27ceda6bc7fdec2e7d79a6e4fe16ffdf")

ctd = ctd_edi%>% #format
  mutate(Date = as.Date(DateTime, format = "%Y-%m-%d %H:%M:%S"))
```


Heatmap
```{r}
#Decrease dataset size by trimming to 0.1m depth intervals
depths <- seq(0,11, by = .1)
newDepths <- depths
df.final.init<- ctd %>% group_by(Date, Reservoir, Site) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[1]))) #Create a new dataframe
df.final.init$Depth_m <- newDepths[1]
for (i in 2:length(depths)){ #loop through all depths and add the closest values to the final dataframe
  ctd_atThisDepth <- ctd %>% group_by(Date, Reservoir, Site) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[i])))
  ctd_atThisDepth = ctd_atThisDepth%>%
    filter(abs(Depth_m-newDepths[i])<0.1) #only include if the measured depth is within 0.1 of the depth we are labeling it
  ctd_atThisDepth$Depth_m <- newDepths[i]
  df.final.init <- rbind(df.final.init,ctd_atThisDepth)
}
df.final.raw = df.final.init%>%
  filter(Reservoir=="BVR")

#Load YSI data from EDI
ysi <- read.csv("https://pasta.lternet.edu/package/data/eml/edi/198/9/b3bd353312f9e37ca392e2a5315cc9da")

#Format YSI data
ysi_formatted = ysi%>%
  filter(#!is.na(DO_mgL),
         Site == 50,
         Reservoir=="BVR")%>% #Only the deepest site
  mutate(Date = as.Date(DateTime))%>%
  select("Reservoir", "Site", "Date", "Depth_m", "DO_mgL", "DOSat", "Temp_C", "pH")%>%
  #We are only using YSI to fill in gaps in CTD data. Select data for those gaps here
  filter(year(Date)==2021)%>%
  mutate(DO_mgL = ifelse(Date<=as.Date("2021-07-01")|Date>=as.Date("2021-12-01"),NA,DO_mgL),
         DO_pSat = ifelse(Date<=as.Date("2021-07-01")|Date>=as.Date("2021-12-01"),NA,DOSat),
         Temp_C = ifelse(Date<=as.Date("2021-07-01")|Date>=as.Date("2021-12-01"),NA,Temp_C))%>%
  mutate(method = "ysi")%>%
  select(-DOSat)%>%
  filter(Date!="2021-05-31"|Depth_m<=10)

Years = 2013:2022
Sites = c(50)

# Combine CTD and YSI data
df.final_export = df.final.raw%>%
  mutate(Date = as.Date(Date),
         Year = year(Date))%>%
  filter(Year %in% Years,
         Site %in% Sites,
         Reservoir == "BVR"
         )%>%
  mutate(DO_mgL = ifelse(Date>as.Date("2021-07-01")&Date<as.Date("2021-12-01"),NA,DO_mgL),
         DOsat_percent = ifelse(Date>as.Date("2021-07-01")&Date<as.Date("2021-12-01"),NA,DOsat_percent))%>%
  full_join(ysi_formatted%>%dplyr::rename(pH_ysi = pH, DO_mgL_ysi = DO_mgL, DO_pSat_ysi = DO_pSat,Temp_C_ysi = Temp_C))%>%
  group_by(Date, Site)%>%
  mutate(max = max(Depth_m),
         pH=ifelse(is.na(pH),pH_ysi,pH),
         DO_mgL=ifelse(is.na(DO_mgL),DO_mgL_ysi,DO_mgL),
         DOsat_percent=ifelse(is.na(DOsat_percent),DO_pSat_ysi,DOsat_percent),
         Depth_m_orig = Depth_m,
         Depth_m = max-Depth_m,
         Turbidity_NTU=ifelse(Turbidity_NTU>10&Depth_m<0.3,NA,Turbidity_NTU),
         Year = year(Date)) #Sediment got mixed up in early 2022

df.final = df.final_export%>%
  filter(max>5)

export = df.final_export%>%
  filter(Reservoir=="BVR",
         Depth_m_orig==0.1)%>%
  dplyr::select(-DateTime)

write.csv(export,"Processed_data/CTD at 0.1m.csv",row.names = F)

cat_long = read.csv("Data/BVR_longoutput_FLARE_2020_2021.csv")%>%
  filter(Sensor=="ThermistorTemp")

sensor_depth = cat_long%>%
  mutate(Year=year(DateTime))%>%
  filter(Reservoir_depth>5,
         Year %in% c(2021,2022))%>%
  mutate(Date = as.Date(DateTime),
         max = max(Reservoir_depth))%>%
  group_by(Date,Year)%>%
  summarize(Reservoir_depth = max(Reservoir_depth),
            max = unique(max))%>%
  select(Date,Reservoir_depth,max,Year)

ctd_sensor = df.final%>%
  select(-DateTime)%>%
  left_join(sensor_depth%>%select(-max))%>%
  group_by(Date)%>%
  mutate(max_ctd = max(Depth_m),
         dif = Reservoir_depth-max_ctd)%>%
  mutate(Depth_m = Depth_m + dif)%>%
  filter(!is.na(Depth_m))

bottom = df.final%>%
  select(-DateTime)%>%
  left_join(sensor_depth%>%select(-max))%>%
  filter(!is.na(Reservoir_depth))%>%
  group_by(Date)%>%
  filter(Depth_m == min(Depth_m))%>%
  mutate(Depth_m = 0)
  
ctd_adj_depth = ctd_sensor%>%
  full_join(bottom)

lines = data.frame(Dates = as.Date(c("2022-06-28", "2022-05-19","2022-05-28", "2022-07-01")), desc = c("closed","opened", "decreasing", "stable"), type = c("close","open","open","close"), status = c("init","init","final","final"), Year = 2022)
lines = lines%>%
  filter(status == "init")
#Re-format for rectangle instead of discrete lines
lines_rect = lines%>%
  select(-type)%>%
  pivot_wider(names_from = desc, values_from = Dates)

vars = c("Temp_C",
         #"Chla_ugL",
         #"Turbidity_NTU",
         #"Cond_uScm",
         #"SpCond_uScm",
         "DO_mgL",
         "DOsat_percent"
         #"pH",
         #"ORP_mV",
         #"PAR_umolm2s",
         #"DescRate_ms"
         )
names = c("Temperature (ºC)", 
          #"Chlorophyll-a (ug/L)", 
          #"Turbidity (NTU)", 
          #Conductivity (µScm)", 
          #Specific Conductance (µScm)",
          "Dissolved Oxygen\n(mg/L)",
          "DO Saturation (%)"
          #"pH",
          #"ORP (mV)",
          #"PAR (umol/m2/s)",
          #"Descent Rate (m/s)"
          )
#vars = c("Turb_NTU")

color_freya = c("#313695", "#4575b4", "#74add1","#abd9e9", "#e0f3f8", "#ffffbf", "#fee090","#fdae61", "#f46d43", "#d73027", "#a50026")

for(i in 1:length(vars)){
  var = vars[i]
  interp = data.frame(x = NA, y = NA, z = NA, Site = NA)
  for(site in Sites){
    for(year in Years){
      bvr<- ctd_adj_depth%>%
        mutate(Year = year(Date),
               Date = as.Date(Date))%>%
        filter(Reservoir == "BVR",
               !is.na(get(var)),
               !is.na(Depth_m),
               Site %in% Sites,
               Year %in% Years)%>%
        group_by(Site)%>%
        mutate(max = max(Depth_m))
      bvr_site<- bvr%>%
        filter(Site == site,
               Year == year)
      if(nrow(bvr_site)>0){
        bvr_interp <- interp2xyz(interp(bvr_site$Date,bvr_site$Depth_m,bvr_site[[var]],xo = seq(min(bvr_site$Date), max(bvr_site$Date), .1),yo = seq(min(bvr_site$Depth_m), max(bvr_site$Depth_m), by = .01), duplicate = "mean"),data.frame = T)
        interp = interp%>%
          full_join(bvr_interp%>%mutate(Site=site))
      }
    }
  }
  interp = interp%>%
    filter(!is.na(Site))
  
  bvr_maxes = bvr%>%
    group_by(Site)%>%
    summarize(max = unique(max))
  
  #sensor_depth_plot = sensor_depth%>%
  #  full_join(bvr_maxes)%>%
  #  filter(Date>= min(bvr$Date),
  #         Date<= max(bvr$Date),
  #         WaterLevel<=max)
  
  #Heatmap
  jpeg(paste0("Figs/BVR_",var,"_heatmap_2022.jpeg"),width = 8, height = 4, units = "in", res = 300)
  p = interp%>%
    mutate(x = as.Date(x, origin = "1970-01-01"),
           Year = year(x))%>%
    ggplot()+
    geom_raster(aes(x=x,fill = z, y=y))+
    scale_y_continuous(expand = c(0,0),limits = c(0, NA))+
    labs(x = "", y = "Height above sediments (m)")+
    scale_fill_gradientn(colours = if(var%in%c("DO_mgL","DO_pSat","ORP_mV")){rev(color_freya)}else{color_freya}, na.value="white", name = names[i])+
    geom_ribbon(data = sensor_depth, aes(x = Date, ymin= Reservoir_depth, ymax = max), fill = "white",color = "black",lwd=.2)+
    geom_point(data = bvr, aes(x = Date, y = max), shape = 25, fill = "black", color = "white", size  =2)+
    geom_rect(aes(xmin = opened,xmax = closed,ymin=-Inf,ymax=Inf),fill = "black", data = lines_rect, alpha = 0.15)+
    geom_vline(data=lines,aes(xintercept = Dates), show.legend = F)+
    geom_hline(aes(yintercept = 6.6, lty = "Out-take pipe"), alpha = 0.3)+
    scale_linetype_manual(values = c("84"),
                          breaks = c("Out-take pipe"),
                          labels = c("Out-take pipe"),  name= NULL)+
    scale_x_date(expand = c(0,0))+
    theme(panel.border = element_rect(fill = NA),
          panel.background = element_rect(fill = "white"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())+
    facet_grid(#rows= vars(Site),
               cols = vars(Year),
               scales = "free",
               space = "free_y")
  print(p)
  dev.off()
}
```

Stratification statisitcs
```{r}
ctd <- read.csv("../CTD_EDI/CTD_2013_2022.csv")%>% #load saved data
  filter(Reservoir=="BVR")%>%
  filter(Site == 50)%>%
  mutate(Date = as.POSIXct(DateTime, format = "%Y-%m-%d %H:%M:%S"))

#Decrease dataset size by trimming to 0.1m depth intervals
depths <- seq(0,11, by = .01)
newDepths <- depths
df.final<- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[1]))) #Create a new dataframe
df.final$Depth_m <- newDepths[1]
for (i in 2:length(depths)){ #loop through all depths and add the closest values to the final dataframe
  ctd_atThisDepth <- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[i])))
  ctd_atThisDepth = ctd_atThisDepth%>%
    filter(abs(Depth_m-newDepths[i])<0.1) #only include if the measured depth is within 0.1 of the depth we are labeling it
  ctd_atThisDepth$Depth_m <- newDepths[i]
  df.final <- rbind(df.final,ctd_atThisDepth)
}

new_depths = df.final%>%
  group_by(Date, Site)%>%
  mutate(Depth_m = max(Depth_m)-Depth_m)

library(rLakeAnalyzer)
strat = df.final%>%
  group_by(Date,Site)%>%
  summarize(buoy_freq = max(buoyancy.freq(Temp_C,Depth_m)),
            thermo = thermo.depth(Temp_C,Depth_m),
            epi = meta.depths(Temp_C,Depth_m)[1],
            hypo = meta.depths(Temp_C,Depth_m)[2],
            tdo3 = Temp_C[which.min(Depth_m[DO_mgL<3])],
            t = Temp_C[which.min(Depth_m)])%>%
  mutate(Year = year(Date))
strat$Date_22 = strat$Date
year(strat$Date_22)=2022

lines = data.frame(Dates = as.Date(c("2022-06-28", "2022-05-19","2022-05-28", "2022-07-01")), desc = c("closed","opened", "decreasing", "stable"), type = c("close","open","open","close"), status = c("init","init","final","final"))

jpeg("Figs/Buoyancy_freq.jpg",res = 300, units = "in",width = 6, height = 4)
strat%>%
  filter(Site==50)%>%
  ggplot(aes(x = Date_22, y = buoy_freq, color = as.factor(Year)))+
  geom_point()+
  ylab("Buoyancy frequency (sec^-2)")+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  xlab("Date")
#+facet_wrap(~Year, scales = "free_x")
dev.off()

jpeg("Figs/Thermo_depth.jpg",res = 300, units = "in",width = 6, height = 4)
strat%>%
  filter(Site==50)%>%
  ggplot(aes(x = Date_22, y = thermo, color = as.factor(Year)))+
  geom_point()+
  geom_line()+
  ylab("Thermocline: depth from surface (m)")+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  xlab("Date")#+facet_wrap(~Site)
dev.off()

jpeg("Figs/Epi_thickness.jpg",res = 300, units = "in",width = 6, height = 4)
strat%>%
  filter(Site==50)%>%
  ggplot(aes(x = Date_22, y = epi, color = as.factor(Year)))+
  geom_point()+
  geom_line()+
  ylab("Epilimnion thickness (m)")+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  xlab("Date")#+facet_wrap(~Site)
dev.off()

oxy = df.final%>%
  filter(DO_mgL<3)%>%
  group_by(Date,Site)%>%
  summarize(tdo3 = Temp_C[which.min(Depth_m)],
            Depth_m = min(Depth_m))%>%
  mutate(Year = as.factor(year(Date)),
         Date_22 = Date)
year(oxy$Date_22)=2022

jpeg("Figs/TDO3.jpg",res = 300, units = "in",width = 6, height = 4)
oxy%>%
  filter(Site==50)%>%
  ggplot(aes(x = Date_22, y = tdo3, color = Year))+
  geom_point()+
  geom_line()+
  ylab("Temperature at which DO > 3")+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  xlab("Date")#+facet_wrap(~Site)
dev.off()

jpeg("Figs/Depth_DO3.jpg",res = 300, units = "in",width = 6, height = 4)
oxy%>%
  filter(Site==50)%>%
  ggplot(aes(x = Date_22, y = Depth_m, color = Year))+
  geom_point()+
  geom_line()+
  ylab("Depth at which DO > 3")+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  scale_y_reverse()+
  xlab("Date")#+facet_wrap(~Site)
dev.off()

bathy = read.csv("Figs/Bathymetry_comb.csv")%>%
  filter(Reservoir == "BVR")

#For some reason schmidt doesn't run unless we filter to 1m
depths <- seq(0,11, by = 1)
newDepths <- depths
df.final.1m<- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[1]))) #Create a new dataframe
df.final.1m$Depth_m <- newDepths[1]
for (i in 2:length(depths)){ #loop through all depths and add the closest values to the final dataframe
  ctd_atThisDepth <- ctd %>% group_by(Date, Reservoir) %>% slice(which.min(abs(as.numeric(Depth_m) - depths[i])))
  ctd_atThisDepth = ctd_atThisDepth%>%
    filter(abs(Depth_m-newDepths[i])<0.1) #only include if the measured depth is within 0.1 of the depth we are labeling it
  ctd_atThisDepth$Depth_m <- newDepths[i]
  df.final.1m <- rbind(df.final.1m,ctd_atThisDepth)
}

ctd_depths = df.final.1m%>%
  mutate(Date = as.Date(Date))%>%
  filter(Site == 50)%>%
  group_by(Date)%>%
  summarize(WaterLevel = max(Depth_m))

flexible_bathy = ctd_depths%>%
  mutate(Reservoir = "BVR")%>%
  full_join(bathy)%>%
  group_by(Date)%>%
  mutate(Depth_m = Depth_m - (max(Depth_m)-unique(WaterLevel)) + 1)%>%
  filter(Depth_m>=0)

site50 = df.final%>%
  filter(Site == 50)

schmidts = c()
for(date in unique(site50$Date)){
  temps = site50%>%
    filter(Date == date)
  baths = flexible_bathy%>%
    filter(Date==date)
  schmidts = c(schmidts, schmidt.stability(wtr = temps$Temp_C, depths = temps$Depth_m, bthA = baths$SA_m2, bthD = baths$Depth_m, sal = rep(0,length(temps$Temp_C))))
}

schmidt_df = data.frame(Date = unique(site50$Date), Schmidt = schmidts)%>%
  mutate(Year = year(Date))
schmidt_df$Date_22 = schmidt_df$Date
year(schmidt_df$Date_22)=2022

jpeg("Figs/Schmidt_stability.jpg", width = 6, height = 4, res = 300, units = "in")
schmidt_df%>%
  mutate(Year = as.factor(Year))%>%
  ggplot(aes(x = Date_22, y = Schmidt, color = Year))+
  geom_point()+
  geom_line()+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("Schmidt stability (J/m^2)")+
  theme_bw()+
  xlab("Date")
dev.off()

jpeg("Figs/Schmidt_stability_blank.jpg", width = 6, height = 4, res = 300, units = "in")
schmidt_df%>%
  mutate(Year = as.factor(Year))%>%
  ggplot(aes(x = Date_22, y = Schmidt, color = Year))+
  geom_point(alpha = 0)+
  geom_line(alpha = 0)+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("Schmidt stability (J/m^2)")+
  theme_bw()+
  xlab("Date")
dev.off()
```


Determine interflow depth
```{r}
ysi = read_excel("2022_YSI_PAR_Profiles.xlsx")%>%
  mutate(Site = as.numeric(Site))

inUrl2  <- "https://pasta.lternet.edu/package/data/eml/edi/198/10/b3bd353312f9e37ca392e2a5315cc9da" 
infile2 <- tempfile()
try(download.file(inUrl2,infile2,method="curl"))
if (is.na(file.size(infile2))) download.file(inUrl2,infile2,method="auto")

                   
 dt2 <-read.csv(infile2,header=F 
          ,skip=1
            ,sep=","  
        , col.names=c(
                    "Reservoir",     
                    "Site",     
                    "DateTime",     
                    "Depth_m",     
                    "Temp_C",     
                    "DO_mgL",     
                    "DOSat",     
                    "Cond_uScm",     
                    "Sp_cond_uScm",     
                    "PAR_umolm2s",     
                    "ORP_mV",     
                    "pH",     
                    "Flag_DateTime",     
                    "Flag_Temp",     
                    "Flag_DO",     
                    "Flag_DOSat",     
                    "Flag_Cond",     
                    "Flag_Sp_Cond",     
                    "Flag_PAR",     
                    "Flag_ORP",     
                    "Flag_pH"    ), check.names=TRUE)%>%
   mutate(DateTime = as.POSIXct(DateTime))
               
unlink(infile2)

ysi_filt = ysi%>%
  full_join(dt2)%>%
  filter(Reservoir == "FCR", 
         Site == "100")%>%
  mutate(Year = as.factor(year(DateTime)),
         Date_22 = DateTime)%>%
  filter(month(DateTime)<=8,
         month(DateTime)>=4)
year(ysi_filt$Date_22)<- 2022

ctd <- read.csv("../CTD_season_csvs/CTD_FCR_2022.csv")%>% #load saved data
  mutate(Date = as.POSIXct(Date, format = "%Y-%m-%dT%H:%M:%SZ"),
         Date = as.Date(Date))

ctd%>%
  filter(Date %in% as.Date(ysi_filt$DateTime))

depths = c()
dates = c()
for(date in as.Date(ysi_filt$DateTime)){
  new = ctd%>%
    filter(Date == date,
           !is.na(Temp_C))
  if(nrow(new)>0){
    dates = c(dates, date)
  }
  temp = ysi_filt$Temp_C[as.Date(ysi_filt$DateTime)==date]
  depths = c(depths,new$Depth_m[which.min(abs(new$Temp_C - temp))])
}
inflow_depth = data.frame(Date = as.Date(dates, origin = "1970-01-01"), Depth_m = depths)

```

CTD and YSI/pH comparison
```{r}
ysi_comp = ysi%>%
  mutate(Date = as.Date(DateTime))%>%
  select("Reservoir",
         "Site",
         "Date",
         "Depth_m",
         "DO_mgL",
         "DOSat",
         "Temp_C",
         "pH")%>%
  #We are only using YSI to fill in gaps in CTD data. Select data for those gaps here
  mutate(method = "ysi")%>%
  filter(Date!="2021-05-31"|Depth_m<=10)

ctd_comp = df.final.init%>%
  mutate(Date = as.Date(Date),
         Year = year(Date))%>%
  mutate(DO_mgL = ifelse(Date>as.Date("2021-07-01")&Date<as.Date("2021-12-01"),NA,DO_mgL),
         DOsat_percent = ifelse(Date>as.Date("2021-07-01")&Date<as.Date("2021-12-01"),NA,DOsat_percent))%>%
  full_join(ysi_comp%>%dplyr::rename(pH_ysi = pH, DO_mgL_ysi = DO_mgL, DO_pSat_ysi = DOSat,Temp_C_ysi = Temp_C))%>%
  group_by(Date, Site)%>%
  mutate(max = max(Depth_m),
         Year = year(Date))%>%
  filter(max>5) 

ysi_comp%>%
  group_by(Date,Depth_m,Site,Reservoir)%>%
  mutate(n=n())%>%
  filter(n>1)%>%
  arrange(Date,Depth_m,Site,Reservoir)

library(plotly)
p = ctd_comp%>%
  ggplot(aes(x = Temp_C_ysi, y= Temp_C, color = Reservoir))+
  geom_point()
ggplotly(p)

ctd_comp%>%
  ggplot(aes(x = DO_mgL_ysi, y= DO_mgL, color = Reservoir))+
  geom_point()

summary(lm(DO_mgL~DO_mgL_ysi,data = ctd_comp))

ctd_comp%>%
  ggplot(aes(x = pH_ysi, y= pH, color = Reservoir))+
  geom_point()

min(df.final$Date[!is.na(df.final$pH)])
max(df.final$Date[!is.na(df.final$pH)])
min(ysi_comp$Date[!is.na(ysi_comp$pH)])
max(ysi_comp$Date[!is.na(ysi_comp$pH)])

df.final%>%
  filter(as.Date(Date)=="2015-06-18")
```


Light attenuation/light extinction
```{r}
#Using the equation here
#https://www.esf.edu/efb/schulz/Limnology/Light.html

ctd <- read.csv("../CTD_EDI/CTD_2013_2022.csv")%>% #load saved data
  filter(Reservoir=="BVR")%>%
  filter(Site == 50)%>%
  mutate(Date = as.POSIXct(DateTime, format = "%Y-%m-%d %H:%M:%S"))

atten_k = ctd%>%
  filter(!is.na(PAR_umolm2s))%>%
  group_by(Date)%>%
  filter(sum(Depth_m<0)>0)%>%
  mutate(I0 = mean(PAR_umolm2s[Depth_m<0], na.rm = T))%>%
  filter(Depth_m>0)%>%
  summarize(I0 = unique(I0),
            k = coef(lm(I(log(PAR_umolm2s)-log(I0))~ 0 + Depth_m)),
            r2 = summary(lm(I(log(PAR_umolm2s)-log(I0))~ 0 + Depth_m))$r.squared,
            Zeu = min(Depth_m[PAR_umolm2s<I0/100]),
            Zeu_0.1 = min(Depth_m[PAR_umolm2s<I0/1000]))%>%
  filter(r2>0.9)

write.csv(atten_k,"../../BVR drawdown/Data/attenuation_calc.csv",row.names = F)

atten_k$Date_22<-atten_k$Date
year(atten_k$Date_22)=2022

lines = data.frame(Dates = as.Date(c("2022-06-28", "2022-05-19","2022-05-28", "2022-07-01")), desc = c("closed","opened", "decreasing", "stable"), type = c("close","open","open","close"), status = c("init","init","final","final"))

jpeg("Figs/Light attenuation.jpg", width = 6, height = 4, res = 300, units = "in")
atten_k%>%
  mutate(Year = as.factor(year(Date)))%>%
  filter(Year%in%c(2022,2021))%>%
  ggplot(aes(x = Date_22, y = k, color = Year))+
  geom_line()+
  geom_point()+
  geom_vline(data=lines,aes(xintercept = as.POSIXct(Dates), lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("Light attenuation coefficient")+
  theme_bw()+
  xlab("")
dev.off()

jpeg("Figs/Euphotic_zone.jpg", width = 6, height = 4, res = 300, units = "in")
atten_k%>%
  mutate(Year = as.factor(year(Date)))%>%
  filter(Year%in%c(2022,2021))%>%
  ggplot(aes(x = Date_22, y = Zeu, color = Year))+
  geom_line()+
  geom_point()+
  geom_vline(data=lines,aes(xintercept = as.POSIXct(Dates), lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  ylab("Euphotic zone depth (m)")+
  theme_bw()+
  xlab("")
dev.off()

summary(ctd$PAR_umolm2s)

#strat is defined in a code chunk above
jpeg("Figs/Zeu_thermo.jpg", width = 6, height = 4, res = 300, units = "in")
strat%>%
  filter(Site==50)%>%
  select(-Date_22)%>%
  mutate(Date = as.Date(Date),
         Year = as.factor(year(Date)))%>%
  full_join(atten_k%>%
              mutate(Date = as.Date(Date)))%>%
  filter(year(Date)%in%c(2021,2022))%>%
  ggplot(aes(x = Date_22, y = Zeu/thermo, color = Year))+
  geom_line()+
  ylab("Euphotic zone:mixed layer depth")+
  xlab("")+
  geom_hline(yintercept = 1)+
  theme_bw()
dev.off()


strat%>%
  filter(Site==50)%>%
  select(-Date_22)%>%
  mutate(Date = as.Date(Date),
         Year = as.factor(year(Date)))

ctd%>%
  filter(!is.na(PAR_umolm2s))%>%
  group_by(Date)%>%
  filter(sum(Depth_m<0)>0)%>%
  mutate(I0 = mean(PAR_umolm2s[Depth_m<0], na.rm = T),
         Date=as.Date(Date))%>%
  filter(Depth_m>0)%>%
  left_join(strat%>%
              filter(Site==50)%>%
              select(-Date_22)%>%
              mutate(Date = as.Date(Date),
                     Year = as.factor(year(Date))))%>%
  filter(!is.na(thermo),
         Depth_m<thermo)%>%
  arrange(Date,Depth_m)%>%
  summarize(I0 = unique(I0),
            thermo_light = last(PAR_umolm2s),
            pct = thermo_light/I0*100)%>%
  filter(year(Date)%in%c(2021,2022))%>%
  ggplot(aes(x = Date, y = pct))+
  geom_point()
```

