---
title: "manual measurements"
author: "Abby Lewis"
date: "2022-07-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(lubridate)
```

```{r}
secchi = read_excel("./Data/2022_Secchi_depth.xlsx")

inUrl1  <- "https://pasta.lternet.edu/package/data/eml/edi/198/10/375f87747001e1681b0e805d00cc1341" 
infile1 <- tempfile()
try(download.file(inUrl1,infile1,method="curl"))
if (is.na(file.size(infile1))) download.file(inUrl1,infile1,method="auto")

                   
 dt1 <-read.csv(infile1,header=F 
          ,skip=1
            ,sep=","  
        , col.names=c(
                    "Reservoir",     
                    "Site",     
                    "DateTime",     
                    "Secchi_m",     
                    "Flag_DateTime",     
                    "Flag_Secchi"    ), check.names=TRUE)%>%
   mutate(DateTime = as.Date(DateTime))
               
unlink(infile1)

secchi_plot = secchi%>%
  full_join(dt1)%>%
  filter(Reservoir == "BVR",
         Site == 50)%>%
  mutate(Year = year(DateTime),
         Date_22 = DateTime)%>%
  filter(month(DateTime)<=8,
         month(DateTime)>=4)
year(secchi_plot$Date_22)<- 2022

lines = data.frame(Dates = as.Date(c("2022-06-28", "2022-05-19","2022-05-28", "2022-07-01")), desc = c("closed","opened", "decreasing", "stable"), type = c("close","open","open","close"), status = c("init","init","final","final"))

jpeg("./Figs/BVR_Secchi.jpg", res = 300, width = 6, height = 4, units = "in")
secchi_plot%>%
  filter(Year%in%c(2021,2022))%>%
  mutate(Year = as.factor(Year))%>%
  ggplot(aes(x = as.Date(Date_22)))+
  geom_line(aes(y = Secchi_m, color = Year))+
  #geom_point(aes(y = Secchi_m, color = Year))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  scale_color_viridis_d()+
  theme_bw()+
  theme(axis.title.x = element_blank())+
  ylab("Secchi depth (m)")
dev.off()

secchi_plot%>%
  group_by(Year)%>%
  summarize(mean = mean(Secchi_m, na.rm = T))%>%
  ggplot(aes(x = Year, y = mean))+
  geom_point()+
  geom_smooth(method= "lm")
```


```{r}
ysi = read_excel("./Data/2022_YSI_PAR_Profiles.xlsx")%>%
  mutate(Site = as.numeric(Site))

inUrl2  <- "https://pasta.lternet.edu/package/data/eml/edi/198/10/b3bd353312f9e37ca392e2a5315cc9da" 
infile2 <- tempfile()
try(download.file(inUrl2,infile2,method="curl"))
if (is.na(file.size(infile2))) download.file(inUrl2,infile2,method="auto")

                   
 dt2 <-read.csv(infile2,header=F 
          ,skip=1
            ,sep=","  
        , col.names=c(
                    "Reservoir",     
                    "Site",     
                    "DateTime",     
                    "Depth_m",     
                    "Temp_C",     
                    "DO_mgL",     
                    "DOSat",     
                    "Cond_uScm",     
                    "Sp_cond_uScm",     
                    "PAR_umolm2s",     
                    "ORP_mV",     
                    "pH",     
                    "Flag_DateTime",     
                    "Flag_Temp",     
                    "Flag_DO",     
                    "Flag_DOSat",     
                    "Flag_Cond",     
                    "Flag_Sp_Cond",     
                    "Flag_PAR",     
                    "Flag_ORP",     
                    "Flag_pH"    ), check.names=TRUE)%>%
   mutate(DateTime = as.POSIXct(DateTime))
               
unlink(infile2)

ysi_filt = ysi%>%
  full_join(dt2)%>%
  filter(Reservoir == "FCR", 
         Site == "100")%>%
  mutate(Year = as.factor(year(DateTime)),
         Date_22 = DateTime)%>%
  filter(month(DateTime)<=8,
         month(DateTime)>=4)
year(ysi_filt$Date_22)<- 2022

jpeg("./Figs/Weir_DO.jpg", res = 300, width = 6, height = 4, units = "in")
ysi_filt%>%
  filter(DOSat != 5.97)%>%
  ggplot(aes(x = as.Date(Date_22)))+
  geom_line(aes(y = DOSat, color = Year))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  scale_color_viridis_d()+
  theme_bw()+
  theme(axis.title.x = element_blank())+
  ylab("DO saturation (%)")
dev.off()

jpeg("./Figs/Weir_DO_mgL.jpg", res = 300, width = 6, height = 4, units = "in")
ysi_filt%>%
  filter(DOSat != 5.97)%>%
  ggplot(aes(x = as.Date(Date_22)))+
  geom_line(aes(y = DO_mgL, color = Year))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  scale_color_viridis_d()+
  theme_bw()+
  theme(axis.title.x = element_blank())+
  ylab("DO concentration (mg/L)")
dev.off()

ysi_filt%>%
  filter(DOSat<60)

jpeg("./Figs/Weir_Temp.jpg", res = 300, width = 6, height = 4, units = "in")
ysi_filt%>%
  #filter(DOSat != 5.97)%>%
  ggplot(aes(x = as.Date(Date_22)))+
  geom_line(aes(y = Temp_C, color = Year))+
  #geom_point(aes(y = Secchi_m, color = Year))+
  geom_vline(data=lines,aes(xintercept = Dates, lty = status), show.legend = F)+
  scale_linetype_manual(values = c("solid","dashed"))+
  scale_color_viridis_d()+
  theme_bw()+
  theme(axis.title.x = element_blank())+
  ylab("Temperature (ºC)")
dev.off()

ysi_filt%>%
  mutate(year_2016 = ifelse(Year==2016,T,F))%>%
  ggplot(aes(x = DO_mgL,y=DOSat, color = Temp_C, shape = year_2016))+
  geom_point()

ysi_filt_22 = ysi_filt%>%
  filter(Year == 2022)
```

