---
title: "Drawdown metals"
author: "Abby Lewis"
date: "7/22/2022"
output: html_document
---

This file loads metals data from EDI and creates a summary output with only values from 0.1 m depth


Step 1: Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```


Step 2: Load, format, and export data
```{r}
metals <- read.csv("https://pasta.lternet.edu/package/data/eml/edi/455/7/e71d70cac1650610e6a3fbbf7928007f")%>%
  mutate(Date = as.Date(DateTime))

metals_surf = metals%>%
  filter(Reservoir == "BVR",
         Depth_m == 0.1,
         Site==50)
  
#Additional QAQC needed (Days where soluble>total)
metals_final = metals_surf%>%
  mutate(TFe_mgL = ifelse(Date=="2022-05-09",
                          metals_surf$SFe_mgL[metals_surf$Date=="2022-05-09"],
                          TFe_mgL),
         TMn_mgL = ifelse(Date=="2022-05-09",
                          metals_surf$SMn_mgL[metals_surf$Date=="2022-05-09"],
                          TMn_mgL),
         SFe_mgL = ifelse(Date=="2022-05-09",
                          metals_surf$TFe_mgL[metals_surf$Date=="2022-05-09"],
                          SFe_mgL),
         SMn_mgL = ifelse(Date=="2022-05-09",
                          metals_surf$TMn_mgL[metals_surf$Date=="2022-05-09"],
                          SMn_mgL),
         TFe_mgL = ifelse(Date=="2022-06-07",
                          NA,
                          TFe_mgL),
         TMn_mgL = ifelse(Date=="2022-06-07",
                          NA,
                          TMn_mgL))

write.csv(metals_final,"../Processed_data/Metals at 0.1m.csv",row.names=F)
```
