---
title: "Physics"
author: "Abby Lewis"
date: "2022-08-30"
output: html_document
---

This file loads meteorological data and creates a summary output for figure 4


Step 1: Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```


Step 2: Load and format meteorological data
```{r}
options(timeout=3000)
met  <- read.csv("https://pasta.lternet.edu/package/data/eml/edi/389/7/02d36541de9088f2dd99d79dc3a7a853")

weather_sum = met%>%
  mutate(DateTime=as_datetime(DateTime),
         Date = as.Date(DateTime),
         Year = year(Date))%>%
  filter(Year %in% c(2021,2022))%>%
  mutate(Year = as.factor(Year))%>%
  group_by(Date,Year)%>%
  summarize(Rain_Total_mm = mean(Rain_Total_mm, na.rm = T),
            AirTemp_C_Average = mean(AirTemp_C_Average,na.rm=T),
            WindSpeed_Average_m_s = mean(WindSpeed_Average_m_s,na.rm=T))%>%
  mutate(DOY = yday(Date))

write.csv(weather_sum, "../Processed_data/Weather_sum.csv", row.names = F)

# create dataset of observations from May 19th - July 1st for 2021 and 2022 for met statisitics
met_drawdown <- met %>%
  select(DateTime, Rain_Total_mm, WindSpeed_Average_m_s, AirTemp_C_Average) %>%
  mutate(DateTime=ymd_hms(DateTime))%>%
  filter((DateTime >= "2021-05-19 00:00:00" & DateTime <= "2021-06-28 00:00:00") |
           (DateTime >= "2022-05-19 00:00:00" & DateTime <= "2022-06-28 00:00:00"))%>%
  mutate(Year=year(DateTime))%>%
  filter(Year %in% c(2021, 2022))

write.csv(met_drawdown, "../Processed_data/Weather_drawdown.csv", row.names = F)
```
