---
title: "CTD"
author: "Abby Lewis"
date: "2023-07-26"
output: html_document
---

1) a heatmap of dissolved oxygen
4 & 5) two fish habitat figures (TDO3 and ZDO3)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

df.final <- read.csv("../Processed_data/CTD trimmed.csv")%>%
  mutate(Date=as.Date(Date))
```


Step 1: Create DO heatmap
```{r}
cat_long = read.csv("../Data/BVR_longoutput_FLARE_2020_2021.csv")%>%
  filter(Sensor == "ThermistorTemp")

sensor_depth = cat_long%>%
  mutate(Year = year(DateTime),
         Date = as.Date(DateTime),
         max = max(Reservoir_depth))%>%
  filter(Reservoir_depth > 5,
         Year %in% c(2021,2022))%>%
  group_by(Date,Year)%>%
  summarize(Reservoir_depth = max(Reservoir_depth),
            max = unique(max))%>%
  select(Date,Reservoir_depth,max,Year)

ctd_sensor <- df.final%>%
  left_join(sensor_depth%>%select(-max))%>%
  group_by(Date)%>%
  mutate(max_ctd = max(Depth_m),
         dif = Reservoir_depth-max_ctd)%>%
  mutate(Depth_m = Depth_m_sed + dif)%>%
  filter(!is.na(Depth_m))

bottom <- df.final%>%
  left_join(sensor_depth%>%select(-max))%>%
  filter(!is.na(Reservoir_depth))%>%
  group_by(Date)%>%
  filter(Depth_m_sed == min(Depth_m_sed))%>%
  mutate(Depth_m = 0)
  
ctd_adj_depth <- ctd_sensor%>%
  full_join(bottom)

lines <- data.frame(Dates = as.Date(c("2022-06-28", "2022-05-19","2022-05-28", "2022-07-01")), desc = c("closed","opened", "decreasing", "stable"), type = c("close","open","open","close"), status = c("init","init","final","final"), Year = 2022)
lines <- lines%>%
  filter(status == "init")
#Re-format for rectangle instead of discrete lines
lines_rect <- lines%>%
  select(-type)%>%
  pivot_wider(names_from = desc, values_from = Dates)

vars <- c("DO_mgL")
names <- c("Dissolved Oxygen\n(mg/L)")
Years <- 2021:2022
Sites <- c(50)

custom_heatmap_palette <- c("#313695", "#4575b4", "#74add1","#abd9e9", "#e0f3f8", "#ffffbf", "#fee090","#fdae61", "#f46d43", "#d73027", "#a50026")

for(i in 1:length(vars)){
  var <- vars[i]
  interp <- data.frame(x = NA, y = NA, z = NA, Site = NA)
  for(site in Sites){
    for(year in Years){
      bvr <- ctd_adj_depth%>%
        mutate(Year = year(Date),
               Date = as.Date(Date))%>%
        filter(Reservoir == "BVR",
               !is.na(get(var)),
               !is.na(Depth_m),
               Site %in% Sites,
               Year %in% Years)%>%
        group_by(Site)%>%
        mutate(max = max(Depth_m))
      bvr_site <- bvr%>%
        filter(Site == site,
               Year == year)
      if(nrow(bvr_site)>0){
        bvr_interp <- interp2xyz(interp(bvr_site$Date,bvr_site$Depth_m,bvr_site[[var]],
                                        xo = seq(min(bvr_site$Date), max(bvr_site$Date), .1),
                                        yo = seq(min(bvr_site$Depth_m), max(bvr_site$Depth_m), 
                                                 by = .01), 
                                        duplicate = "mean"),data.frame = T)
        interp <- interp%>%
          full_join(bvr_interp%>%mutate(Site=site))
      }
    }
  }
  interp <- interp%>%
    filter(!is.na(Site))
  
  bvr_maxes <- bvr%>%
    group_by(Site)%>%
    summarize(max = unique(max))
  
  #Heatmap
  jpeg(paste0("../Figs/BVR_",var,"_heatmap_2022.jpeg"),width = 8, height = 4, units = "in", res = 300)
  p <- interp%>%
    mutate(x = as.Date(x, origin = "1970-01-01"),
           Year = year(x))%>%
    ggplot()+
    geom_raster(aes(x=x,fill = z, y=y))+
    scale_y_continuous(expand = c(0,0),limits = c(0, NA))+
    labs(x = "", y = "Height above sediments (m)")+
    scale_fill_gradientn(colours = if(var%in%c("DO_mgL","DO_pSat","ORP_mV")){rev(custom_heatmap_palette)}else{custom_heatmap_palette}, na.value="white", name = names[i])+
    geom_ribbon(data = sensor_depth, aes(x = Date, ymin= Reservoir_depth, ymax = max), fill = "white",color = "black",lwd=.2)+
    geom_point(data = bvr, aes(x = Date, y = max), shape = 25, fill = "black", color = "white", size  =2)+
    geom_rect(aes(xmin = opened,xmax = closed,ymin=-Inf,ymax=Inf),fill = "black", data = lines_rect, alpha = 0.15)+
    geom_vline(data=lines,aes(xintercept = Dates), show.legend = F)+
    geom_hline(aes(yintercept = 6.6, lty = "Out-take pipe"), alpha = 0.3)+
    scale_linetype_manual(values = c("84"),
                          breaks = c("Out-take pipe"),
                          labels = c("Out-take pipe"),  name= NULL)+
    scale_x_date(expand = c(0,0))+
    theme(panel.border = element_rect(fill = NA),
          panel.background = element_rect(fill = "white"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())+
    facet_grid(cols = vars(Year),
               scales = "free",
               space = "free_y")
  print(p)
  dev.off()
}

```


Step 2: Plot fish habitat suitability metrics
```{r}
oxy <- df.final%>%
  filter(DO_mgL<3)%>%
  group_by(Date,Site)%>%
  summarize(tdo3 = Temp_C[which.min(Depth_m)],
            Depth_m = min(Depth_m))%>%
  mutate(Year = as.factor(year(Date)),
         Date_22 = Date)%>%
  filter(year(Date)%in% c(2021,2022))
year(oxy$Date_22)=2022

lines_rect <- data.frame(closed = as.Date("2022-06-28"), opened = as.Date("2022-05-19"), Year = 2022, year_class = "2022")

jpeg("../Figs/SI_TDO3.jpg",res = 300, units = "in",width = 6, height = 4)
oxy%>%
  filter(Site==50,
         month(Date)>4,
         month(Date)<9)%>%
  ggplot()+
  geom_rect(aes(xmin = opened,xmax = closed,ymin=-Inf,ymax=Inf),
              fill = "grey40", data = lines_rect, alpha = 0.2)+
  geom_point(aes(x = Date_22, y = tdo3))+
  geom_line(aes(x = Date_22, y = tdo3, lty = Year))+
  ylab("Temperature at which DO > 3")+
  scale_linetype_manual(values = c("solid","dashed"))+
  theme_bw()+
  theme(axis.title.x = element_blank())
dev.off()

jpeg("../Figs/SI_Depth_DO3.jpg",res = 300, units = "in",width = 6, height = 4)
oxy%>%
  filter(Site==50,
         month(Date)>4,
         month(Date)<9)%>%
  ggplot()+
  geom_rect(aes(xmin = opened,xmax = closed,ymin=-Inf,ymax=Inf),
              fill = "grey40", data = lines_rect, alpha = 0.2)+
  geom_point(aes(x = Date_22, y = Depth_m))+
  geom_line(aes(x = Date_22, y = Depth_m, lty = Year))+
  ylab("Depth at which DO > 3")+
  scale_linetype_manual(values = c("solid","dashed"))+
  scale_y_reverse(lim = c(NA,0))+
  theme_bw()+
  theme(axis.title.x = element_blank())
dev.off()
```
