---
title: "NID"
author: "Abby Lewis"
date: "2023-06-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

dams <- read_csv("../Raw_external_data/NID_YearCompleted_SurfaceArea_State.csv") %>% 
  rename(SURFACE_AREA = "SURFACE_AREA (acres)") %>% 
  filter(SURFACE_AREA != 0)

dam_facts <- dams %>%
  summarize(med_start_year = median(YEAR_COMPLETED, na.rm = T),
            mean_start_year = mean(YEAR_COMPLETED, na.rm = T),
            med_area_km2 = median(SURFACE_AREA/247.1, na.rm = T),# dividing by 247 converts from acres to km2
            mean_area_km2 = mean(SURFACE_AREA/247.1, na.rm = T),
            max_start_year = max(YEAR_COMPLETED, na.rm = T),
            min_start_year = min(YEAR_COMPLETED, na.rm = T),
            max_area_km2 = max(SURFACE_AREA/247.1, na.rm = T),
            min_area_km2 = min(SURFACE_AREA/247.1, na.rm = T))

quantile(dams$SURFACE_AREA/247.1, probs=seq(.925,.926,0.0001))
#92.5% of dams in the US are 1 km2 or smaller

label = data.frame(x = 1.5, y = 15000, label = as.character(as.expression(paste("1  km^{2}"))))
jpeg("../Figs/NID_histogram.jpg",res=300,width = 3, height=3, units = "in")
dams%>%
  ggplot(aes(x = SURFACE_AREA/247))+
  geom_histogram()+
  geom_vline(xintercept=1)+
  scale_x_log10()+
  theme_bw()+
  xlab(expression(paste("Surface area (", m^{2},")")))+
  ylab("Number of dams")+
  annotate(x = 1.5, y = 15000, label = expression(paste("1 ", km^{2})), hjust = "left", geom = "text")
dev.off()
```

